### ISSUE TITLE
Internal server error on opening page

### ISSUE THREAD

**Issue by kurt-stolle** [psychobunny/nodebb-plugin-custom-pages#10]
I get the following error when I go to one of my custom pages

    Internal server error
    /mypage
    Failed to lookup view "mypage" in views directory "NodeBB/public/templates"

**Comment by frenchja** [comment]
@psychobunny I get a similar error on https://github.com/NodeBB/NodeBB/commit/1b88a6a5239b16fc91a8559ad1e03d3bc92a7013 with Persona.  Specifically, the route doesn't seem to survive multiple restarts, just one:

```
29/5 04:14 [13002] - error:  Error: Failed to lookup view "doughyguy" in views directory "/home/ubuntu/NodeBB/public/templates"
    at EventEmitter.app.render (/home/ubuntu/NodeBB/node_modules/express/lib/application.js:555:17)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/node_modules/express/lib/response.js:938:7)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/src/middleware/middleware.js:324:10)
    at renderCustomPage (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-custom-pages/library.js:12:6)
    at Layer.handle [as handle_request] (/home/ubuntu/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ubuntu/NodeBB/node_modules/express/lib/router/route.js:110:13)
    at /home/ubuntu/NodeBB/src/middleware/middleware.js:188:5
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:160:6
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:180:4
    at Object.translator.load (/home/ubuntu/NodeBB/public/src/modules/translator.js:209:5)
29/5 04:14 [13002] - error: /doughyguy
 Error: Failed to lookup view "doughyguy" in views directory "/home/ubuntu/NodeBB/public/templates"
    at EventEmitter.app.render (/home/ubuntu/NodeBB/node_modules/express/lib/application.js:555:17)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/node_modules/express/lib/response.js:938:7)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/src/middleware/middleware.js:324:10)
    at renderCustomPage (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-custom-pages/library.js:12:6)
    at Layer.handle [as handle_request] (/home/ubuntu/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ubuntu/NodeBB/node_modules/express/lib/router/route.js:110:13)
    at /home/ubuntu/NodeBB/src/middleware/middleware.js:188:5
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:160:6
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:180:4
    at Object.translator.load (/home/ubuntu/NodeBB/public/src/modules/translator.js:209:5)
```

**Comment by frenchja** [comment]
After some further testing, only the *last* event saved in the ACP panel persists.  So if I alter or add a new page, only that new page remains post-restart in `public/templates`.  If I `cp` the template to force the route, it's eventually deleted by a cron job.

**Comment by shady2k** [comment]
I have the same problem here as @frenchja.

**Comment by rbeer** [comment]
The '[templates:compiled](https://github.com/NodeBB/NodeBB/blob/master/src/meta/templates.js#L123-L133)' event is emited before 'static:app.load' (i.e. plugins init()).
@shady2k @frenchja 
Please let me know whether the changes work, so I can PR them. :)
https://github.com/rbeer/nodebb-plugin-custom-pages/tree/tplCopyIssue

**Comment by frenchja** [comment]
I switched the remote and restarted NodeBB:
```
git remote -v
origin	git@github.com:rbeer/nodebb-plugin-custom-pages.git (fetch)
origin	git@github.com:rbeer/nodebb-plugin-custom-pages.git (push)
```

Unfortunately, the behavior persists.  Deleting and re-adding route B causes route A to not resolve, despite still being in the panel:
```
5/7 14:07 [18361] - error:  Error: Failed to lookup view "doughyguy" in views directory "/home/ubuntu/NodeBB/public/templates"
    at EventEmitter.app.render (/home/ubuntu/NodeBB/node_modules/express/lib/application.js:555:17)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/node_modules/express/lib/response.js:938:7)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/src/middleware/middleware.js:324:10)
    at renderCustomPage (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-custom-pages/library.js:12:6)
    at Layer.handle [as handle_request] (/home/ubuntu/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ubuntu/NodeBB/node_modules/express/lib/router/route.js:110:13)
    at /home/ubuntu/NodeBB/src/middleware/middleware.js:188:5
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:160:6
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:180:4
    at Object.translator.load (/home/ubuntu/NodeBB/public/src/modules/translator.js:209:5)
5/7 14:07 [18361] - error: /doughyguy
 Error: Failed to lookup view "doughyguy" in views directory "/home/ubuntu/NodeBB/public/templates"
    at EventEmitter.app.render (/home/ubuntu/NodeBB/node_modules/express/lib/application.js:555:17)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/node_modules/express/lib/response.js:938:7)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/src/middleware/middleware.js:324:10)
    at renderCustomPage (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-custom-pages/library.js:12:6)
    at Layer.handle [as handle_request] (/home/ubuntu/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ubuntu/NodeBB/node_modules/express/lib/router/route.js:110:13)
    at /home/ubuntu/NodeBB/src/middleware/middleware.js:188:5
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:160:6
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:180:4
    at Object.translator.load (/home/ubuntu/NodeBB/public/src/modules/translator.js:209:5)
5/7 14:07 [18361] - error:  Error: Failed to lookup view "doughyguy" in views directory "/home/ubuntu/NodeBB/public/templates"
    at EventEmitter.app.render (/home/ubuntu/NodeBB/node_modules/express/lib/application.js:555:17)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/node_modules/express/lib/response.js:938:7)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/src/middleware/middleware.js:324:10)
    at renderCustomPage (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-custom-pages/library.js:12:6)
    at Layer.handle [as handle_request] (/home/ubuntu/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ubuntu/NodeBB/node_modules/express/lib/router/route.js:110:13)
    at /home/ubuntu/NodeBB/src/middleware/middleware.js:188:5
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:160:6
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:180:4
    at Object.translator.load (/home/ubuntu/NodeBB/public/src/modules/translator.js:209:5)
5/7 14:07 [18361] - error: /doughyguy
 Error: Failed to lookup view "doughyguy" in views directory "/home/ubuntu/NodeBB/public/templates"
    at EventEmitter.app.render (/home/ubuntu/NodeBB/node_modules/express/lib/application.js:555:17)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/node_modules/express/lib/response.js:938:7)
    at ServerResponse.res.render (/home/ubuntu/NodeBB/src/middleware/middleware.js:324:10)
    at renderCustomPage (/home/ubuntu/NodeBB/node_modules/nodebb-plugin-custom-pages/library.js:12:6)
    at Layer.handle [as handle_request] (/home/ubuntu/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ubuntu/NodeBB/node_modules/express/lib/router/route.js:110:13)
    at /home/ubuntu/NodeBB/src/middleware/middleware.js:188:5
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:160:6
    at /home/ubuntu/NodeBB/public/src/modules/translator.js:180:4
    at Object.translator.load (/home/ubuntu/NodeBB/public/src/modules/translator.js:209:5)
```

**Comment by rbeer** [comment]
@frenchja 
I'm almost sure you implied this step, but after changing the remote, you also pulled the changes from the repo, didn't you?
Please bear in mind, that you would have to pull from `tplCopyIssue` not `master`, to get the changes (i.e. `git pull origin tplCopyIssue` ). My master-branch is the same as here. :)

**Comment by frenchja** [comment]
I had checked out from master, but I switched branches:
```
commit 7e7721c0a56a864b0a856078f9deb214c502e440
Author: Raphael Beer <raphaelbeer030@gmail.com>
Date:   Sun Jul 5 04:10:27 2015 +0200

    naming the 'plugin'

commit bc74794fe2a1cf48c9f5a6f498644ad079234ef0
Author: Raphael Beer <raphaelbeer030@gmail.com>
Date:   Sun Jul 5 04:06:58 2015 +0200

    :bug: hooking 'templates:compiled' early
```

LGTM.  Nicely done, sir.

**Comment by rbeer** [comment]
:+1: :smiley:

**Comment by henrywright** [comment]
I'm experiencing the same problem outlined [here](https://cloud.githubusercontent.com/assets/720035/7876359/eb416768-058f-11e5-9c81-b0904844f373.png) by @frenchja.

NodeBB 0.7.2 & Redis database running on Nginx in Ubuntu 14.04

**Comment by rbeer** [comment]
@henrywright 
Did you try it with the changes in my repo? My pull request hasn't been merged here, yet.

**Comment by henrywright** [comment]
@rbeer Thanks, I haven't tried yet but will do. Do you know when I'll be able to upgrade the plugin through APC?

**Comment by henrywright** [comment]
@rbeer your changes worked! Now all I have to work out is how to integrate them with the APC plugin?

**Comment by julianlam** [comment]
#18 resolves this
