### ISSUE TITLE
Object # has no method 'csrfToken'

### ISSUE THREAD

**Issue by TedRinehart** [psychobunny/nodebb-plugin-custom-pages#5]
Running latest dev of NBB as of posting.
This issue only occurs when navigating directly to a custom page. If you navigate to another page on the forum, then access the custom page, the page renders properly.

```
30/11 17:55 [27226] - error: /test
 TypeError: Object #<IncomingMessage> has no method 'csrfToken'
    at Object.apiController.getConfig (/home/tedtest/nbb/src/controllers/api.js:55:2
6)
    at Object.async.parallel.config (/home/tedtest/nbb/src/middleware/middleware.js:
202:20)
    at /home/tedtest/nbb/node_modules/async/lib/async.js:583:25
    at /home/tedtest/nbb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/tedtest/nbb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/home/tedtest/nbb/node_modules/async/lib/async.js:124:9)
    at _parallel (/home/tedtest/nbb/node_modules/async/lib/async.js:582:20)
    at Object.async.parallel (/home/tedtest/nbb/node_modules/async/lib/async.js:598:
9)
    at middleware.buildHeader (/home/tedtest/nbb/src/middleware/middleware.js:200:8)
```

**Comment by TedRinehart** [comment]
Turns out this was an issue in core, not with the plugin.
